def test_arbitrary_file_disclosure_1(setup_profile, try_connect):
    # Arrange
    cobbler_api = try_connect("http://localhost/cobbler_api")

    # Act
    profiles = cobbler_api.get_profiles()
    target = profiles[0]["name"]
    try:
        result = cobbler_api.generate_script(target, "", "/etc/shadow")

        # Assert this NOT succeeds
        assert not result.startswith("root")
    except xmlrpc.client.Fault as e:
        # We have no way of exactly knowing what is in there but if its a ValueError we most likely caught the exploit
        # before something happened.
        assert "ValueError" in e.faultString
