def test_creating_user_with_existing_name_fails():
    """Tests creating a user with an existing username fails."""
    zen_store = Client().zen_store

    with UserContext() as existing_user:
        with pytest.raises(EntityExistsError):
            zen_store.create_user(
                UserRequest(name=existing_user.name, password="password")
            )

    with ServiceAccountContext() as existing_service_account:
        with does_not_raise():
            user = zen_store.create_user(
                UserRequest(
                    name=existing_service_account.name, password="password"
                )
            )
            # clean up
            zen_store.delete_user(user.id)
